In [1]:
# HW2
# Due: 10/22/2020 (Thursday) 12:00PM
# Email to: jzhang@eastwest.edu


# Problem 1:

# A list numbers of rang 0 to 100 to represent 20 student final scores
# 1) Use numpy to show the average score, highest score and lowest score
# 2) Use numpy's boolean index to count how many A (100 - 90), B(89-80), C(79-70), D(69-60), F(<60)
#   (Hint: Bs = data[(data>=80) & (data <90) ])


import numpy as np

# 20 students final scores
#data = np.random.randn(100)  

data = np.random.randint(0, 100, 20)  # start, end, number

scores = [88 ,79, 72, 75, 93, 68, 46, 97, 62, 97, 93, 66, 51, 58,  68 ,  61, 
        72 , 83, 46 ,76]

data = np.array(scores)
print (data)
print(data.shape)
As = data[data>=90]
Bs = data[(data>=80) & (data<=90)]
Cs = data[(data>=70) & (data<=80)]
Ds = data[(data>=60) & (data<=70)]
Fs = data[(data< 60)]
print(data)
print( 'As:' ,len(As))
print( 'Bs:' ,len(Bs))
print( 'Cs:' ,len(Cs))
print( 'Fs:' ,len(Fs))



[88 79 72 75 93 68 46 97 62 97 93 66 51 58 68 61 72 83 46 76]
(20,)
[88 79 72 75 93 68 46 97 62 97 93 66 51 58 68 61 72 83 46 76]
As: 4
Bs: 2
Cs: 5
Fs: 4


In [2]:

# Problem 2:
# Six homework scores from five student , show the each student total scores by the weights and their grades

WEIGHTS = np.array( [0.1, 0.1,0.1,0.2, 0.2, 0.3 ])

# test perfect score
full_score = np.ones(6)*100
#full_score = 100
print(full_score)


#student homework
# Read six homework, from 5 studennts
scores = np.array([[58, 96, 65, 78.5, 76, 89],
                 [58, 96, 65, 78.5, 76, 79],
                 [58, 86, 95, 72.5, 86, 61],
                 [68, 56, 45, 67.5, 96, 82],
                 [68, 96, 65, 78.5, 56, 49]] )

print(scores.shape)

num_student = len(scores)
final_scores = np.zeros(len(scores))

print("# Method 1") 
for i in range(num_student):
    final_score[i] = np.sum(scores[i]*WEIGHTS)
    print(final_scores)

print("# Method 2") 
final_scores = (scores*WEIGHTS)
print(final_scores)

#scores for each student
scores =final_scores.sum(axis = 1)
print(scores)

# Average scores

scores = final_scores.mean(axis =0)
print(scores)



[100. 100. 100. 100. 100. 100.]
(5, 6)
# Method 1


NameError: name 'final_score' is not defined

In [ ]:
# Problem 3 (Option)


# Generate 30 students final scores
# Use bar chart to present the distribution of grades ( See example Chapter 7, use plt.bar )


import numpy as np
data = np.random.randint(0, 100, 30)  # start, end, number

data = np.array(data)

labels = ['A', 'B','C','D','F']
count_grade = np.zeros(5)
count_grade = count_grade.astype(np.int32)


In [ ]:
# page 392
import matplotlib.pyplot as plt

def drawBar(count, labels):
    left_edges = [0, 10, 20, 30, 40 ]
    
    # Create a list
    bar_width = 5
    
    plt.bar(left_edges , count, bar_width, color='Green' )   # 'Red'
    
    plt.xticks([5, 15, 25, 35, 45],labels)
    plt.xlabel('Grade')
    plt.title('Student Final Grade')
    
    plt.show()

drawBar(count_grade, labels)

In [ ]:
# Generate 100 interger
# Use bar chart to present the distribution of from 0-9, 10-19, 20-29, ...,90-99

import numpy as np
data = np.random.randint(1, 101, 50)  # start, end, number
print (data)
data = np.array(data)

labels=['-']*10
print(labels)

for i in range(10):
    labels[i] = str(i*10) + 's'
print(labels)

count= np.zeros(10)
print (count)

# from A to D grade
catoff = 10
for i in range(10):
    condition = (data>= i*10) & ( data < cutoff *(i+1)) 
    count[i]= len(data[condition])
 

# 
print (count)



In [ ]:
import matplotlib.pyplot as plt

# Create a list

left_edges = range(0,100,10)
xMarks=range(0,110,10)
print(left_edges)
print(xMarks)
left_edges
bar_width = 5
    
plt.bar(left_edges , count, bar_width, color='Green' )   # 'Red'
    
plt.xticks(xMarks,labels)
plt.xlabel('Data Distribution')
plt.title('Data Distribution')
    
plt.show()

In [ ]:
# page 392
import matplotlib.pyplot as plt

def main():
    left_edges = [0, 10, 20, 30, 40 ]
    
    # Create a list
    heights = [100, 200, 300, 400, 500]
    bar_width = 5
    
    plt.bar(left_edges , heights, bar_width, color='Green' )   # 'Red'
    
    plt.xticks([5, 15, 25, 35, 45], ['2016', '2017','2018','2019','2020'])
    plt.yticks([100, 200, 300, 400, 500], ['$0m', '$1m','$2m','$3m','$4m','$5m'])
    
    plt.show()

main()

In [ ]:
#help(np.random.randn)
#numpy.random.random(size=None) , Return random floats in the half-open interval [0.0, 1.0).
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.random.html